In [2]:
import numpy as np 
arr = np.arange(10,51,5)
print(arr)

[10 15 20 25 30 35 40 45 50]


In [3]:
arrz = np.zeros((4,6))
arrz[2] = 99
print(arrz)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [99. 99. 99. 99. 99. 99.]
 [ 0.  0.  0.  0.  0.  0.]]


In [4]:
arr = np.array([12, 45, 7, 19, 88, 3, 56, 91, 24, 67])
print (arr[arr > 50])

[88 56 91 67]


In [5]:
arr = np.eye(5)
print(arr)
print(arr*[10,20,30,40,50])

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[10.  0.  0.  0.  0.]
 [ 0. 20.  0.  0.  0.]
 [ 0.  0. 30.  0.  0.]
 [ 0.  0.  0. 40.  0.]
 [ 0.  0.  0.  0. 50.]]


In [6]:
x = np.arange(1,21).reshape(4,5)
print (x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [7]:
print(x[-2:])

[[11 12 13 14 15]
 [16 17 18 19 20]]


In [8]:
print(x[:,2])

[ 3  8 13 18]


In [9]:
print(x[:3, 2:])

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [10]:
a = np.array([1,2,3,4])
b = np.array([[10],[20],[30]])

result = a + b

print(result)
print(result.shape)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
(3, 4)


In [11]:
data = np.array([150, 220, 90, 300, 180, 45])

nor = (data - data.min()) / (data.max() - data.min())

print(nor)

[0.41176471 0.68627451 0.17647059 1.         0.52941176 0.        ]


In [12]:
data = np.array([150, 220, 90, 300, 180, 45])
z_score = (data - data.mean()) / data.std()
print(z_score)

[-0.16988961  0.66956492 -0.88942206  1.62894153  0.18987662 -1.42907141]


In [13]:
mat = np.array([
    [4, 8, 1, 12],
    [7, 3, 9, 5],
    [11, 2, 6, 10],
    [15, 0, 14, 13]
])
rmean = mat.mean(axis=1)
print(rmean)

[ 6.25  6.    7.25 10.5 ]


In [14]:
csum = mat.sum(axis=0)
print(csum)

[37 13 30 40]


In [15]:
maxv = mat.max()
pos = np.unravel_index(np.argmax(mat), mat.shape)
print(maxv)
print(pos)

15
(np.int64(3), np.int64(0))


In [16]:
arr = np.arange(36).reshape(3,4,3)
print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [17]:
arr = np.arange(1,17).reshape(4,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [18]:
revarr = arr[::-1, ::-1]
print(revarr)

[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [19]:
ages = np.array([23, 45, 19, 34, 28, 51, 17, 39])
names = np.array(["Ali", "Sara", "Omar", "Lina", "Khaled", "Nour", "Yara", "Hassan"])
result = names[(ages >= 25) & (ages <= 40)]
print(result)

['Lina' 'Khaled' 'Hassan']


In [20]:
ages = np.array([23, 45, 19, 34, 28, 51, 17, 39])
ages[ages < 20] = 20
print(ages)

[23 45 20 34 28 51 20 39]


In [21]:
np.random.seed(123)
arr = np.random.randint(1, 101, (6,6))
print(arr)

[[ 67  93  99  18  84  58]
 [ 87  98  97  48  74  33]
 [ 47  97  26  84  79  37]
 [ 97  81  69  50  56  68]
 [  3  85  40  67  85  48]
 [ 62  49   8 100  93  53]]


In [22]:
arr = np.random.normal(100, 15, 10)
print(arr)

[127.06686834  85.51674961  80.25279948  90.61322265  95.09580659
  95.37686206 112.40676196 116.06172126  54.16633874 115.08897902]


In [24]:
colors = ["red", "blue", "green", "yellow", "purple"]
res = np.random.choice(colors, 3, replace=False)
print(res)

['red' 'blue' 'green']


In [29]:
arr = np.arange(1, 21)
np.random.shuffle(arr)
print(arr)

[ 3  1 19 13  4  5  6 12 17 10 11  8 18 16  2  7 15  9 20 14]
